"""Crea tabella Sostituzione

Revision ID: 19b4a7f7b0a6
Revises: 
Create Date: 2025-05-10 21:54:06.160790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b4a7f7b0a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sostituzione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_sostituzione', sa.Date(), nullable=False),
    sa.Column('slot_ora', sa.String(length=20), nullable=False),
    sa.Column('materia_originale', sa.String(length=100), nullable=True),
    sa.Column('classe_originale', sa.String(length=20), nullable=True),
    sa.Column('aula_originale', sa.String(length=50), nullable=True),
    sa.Column('docente_assente_email', sa.String(length=120), nullable=False),
    sa.Column('docente_sostituto_email', sa.String(length=120), nullable=False),
    sa.Column('timestamp_conferma', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sostituzione')
    # ### end Alembic commands ###
