"""Aggiungi campi a Sostiruzione per dettagli conferma

Revision ID: 209fa4c31231
Revises: 19b4a7f7b0a6
Create Date: 2025-05-11 10:04:43.969541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209fa4c31231'
down_revision = '19b4a7f7b0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sostituzione', schema=None) as batch_op:
        batch_op.add_column(sa.Column('giorno_settimana', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tipo_suggerimento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dettaglio_suggerimento', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sostituzione', schema=None) as batch_op:
        batch_op.drop_column('dettaglio_suggerimento')
        batch_op.drop_column('tipo_suggerimento')
        batch_op.drop_column('giorno_settimana')

    # ### end Alembic commands ###
